#!/usr/bin/bash


casaversion ()  {

    ver=$1

    # check if $ver is set. if not check if CASA_VERSION is set. if not show link to casa version
    if [[ -z "$ver" ]]; then
        if [ -z "$CASA_VERSION" ]; then
            echo "CASA_VERSION is not set. Use casaversion X to set version"
            echo "use casaversion 4 for casa 4.5.3"
            echo "use casaversion 5 for casa 5.6.1"
            echo "use casaversion 6 for casa 6.2.1"
            echo "Current links to casa versions:"
            ls -lht ~/casa
            ls -lht ~/.casa
        else
            echo "current version is: $CASA_VERSION"
            ls -lht ~/casa
            ls -lht ~/.casa
        fi
        return 0
    fi

    cd $HOME

    if [[ $ver -eq 4 ]]
    then
        rm -f ~/casa
        rm -f ~/.casa
        CASA_VERSION=4.5.3
        export CASA_VERSION
        ln -s ~/data/casa453pipe casa
        ln -s ~/.casa453 .casa
    elif [[ $ver -eq 5 ]]
    then
        rm -f ~/casa
        rm -f ~/.casa
        CASA_VERSION=5.6.1
        export CASA_VERSION
        ln -s ~/data/casa561pipe casa
        ln -s ~/.casa561 .casa
    elif [[ $ver -eq 6 ]]
    then
        rm -f ~/casa
        rm -f ~/.casa
        CASA_VERSION=6.2.1
        export CASA_VERSION
        ln -s ~/data/casa621pipe casa
        ln -s ~/.casa621 .casa
    else
        echo "invalid version"
        echo "current CASA_VERSION is: $CASA_VERSION"
        echo "current links are"
        ls -lht ~/casa
        ls -lht ~/.casa
        return 0
    fi


    echo Setting CASA to verion $CASA_VERSION
    # ls -lht ~/casa
    # ls -lht ~/.casa
    cd $OLDPWD

}


