#!/usr/bin/bash

# starlink eao installation
echo "To run starlink programs run <<starlink>> in the terminal"
echo "this may break programs like CASA. So be sure to run in it's own terminal"
# add starlink to path
if [ -z "$STARLINK_DIR" ]; then
    export STARLINK_DIR=/home/joarlewi/star-2021A
    source $STARLINK_DIR/etc/profile
fi